# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UNLxhc5w90qNVCaz70IUIqVAeVNiMLZS
"""

from flask import Flask, render_template, request
from datetime import datetime, timedelta
import firebase_admin
from firebase_admin import credentials, firestore

app = Flask(__name__)

# Inicializar Firebase
cred = credentials.Certificate("serviceAccountKey.json")
firebase_admin.initialize_app(cred)
db = firestore.client()

# Diccionario de empleados (nombre -> UID)
empleados = {
    "Edson Fernando Herrera Castillo": "kvK4IZNfpGRpKDiwlRgl7JdasNu2",
    "Mauro Mauricio Castañeda": "rOr6WiZuK7QE0ac067EiccvGBWu2",
    "Luis Luisin Carrillo": "rfE9ZoOo69guyH2PU3JGRtT5A2h2"
}

# Función para generar rango de fechas
def fechas_entre(inicio, fin):
    fechas = []
    while inicio <= fin:
        fechas.append(inicio.strftime("%Y-%m-%d"))
        inicio += timedelta(days=1)
    return fechas

# Contar asistencias, retardos y faltas
def resumen_empleado(uid, fechas):
    asistencias = retardos = faltas = 0
    for fecha in fechas:
        doc_ref = db.collection("asistencias").document(uid).collection("asistencias").document(fecha)
        doc = doc_ref.get()
        if doc.exists:
            estado = doc.to_dict().get("estado", "puntual")
            if estado == "retardo":
                retardos += 1
            else:
                asistencias += 1
        else:
            faltas += 1
    return asistencias, retardos, faltas

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/resumen', methods=['POST'])
def resumen():
    fecha_inicio = datetime.strptime(request.form['inicio'], "%Y-%m-%d")
    fecha_fin = datetime.strptime(request.form['fin'], "%Y-%m-%d")
    fechas = fechas_entre(fecha_inicio, fecha_fin)

    resultados = []
    for nombre, uid in empleados.items():
        asistencias, retardos, faltas = resumen_empleado(uid, fechas)
        resultados.append({
            "nombre": nombre,
            "asistencias": asistencias,
            "retardos": retardos,
            "faltas": faltas
        })

    return render_template('resultado.html', datos=resultados, inicio=request.form['inicio'], fin=request.form['fin'])

if __name__ == '__main__':
    app.run(debug=True)